/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.*;

/**
 *
 * @author alumnogreibd
 */
public class VForos extends javax.swing.JFrame {
    
    FachadaAplicacion fa;
    Usuario usuario;
    int idProyecto;

    /**
     * Creates new form VForos
     * @param fa
     * @param usuario
     */
    public VForos(FachadaAplicacion fa, Usuario usuario, int idProyecto) {
        this.fa = fa;
        this.usuario = usuario;
        initComponents();
        
        if (usuario.getTipoUsuario() == TipoUsuario.Normal){
            btnNuevoForo.setVisible(false);
            btnBorrarForo.setVisible(false);
        }
        
        fa.obtenerForos(idProyecto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaForos = new javax.swing.JList<>();
        btnSalir = new javax.swing.JButton();
        btnEntrarForo = new javax.swing.JButton();
        btnNuevoForo = new javax.swing.JButton();
        btnBorrarForo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Foros");

        listaForos.setModel(new ModeloListaStrings());
        jScrollPane1.setViewportView(listaForos);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEntrarForo.setText("Entrar");

        btnNuevoForo.setText("Nuevo Foro");
        btnNuevoForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoForoActionPerformed(evt);
            }
        });

        btnBorrarForo.setText("Borrar Foro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEntrarForo)
                        .addGap(27, 27, 27)
                        .addComponent(btnNuevoForo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrarForo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnEntrarForo)
                    .addComponent(btnNuevoForo)
                    .addComponent(btnBorrarForo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoForoActionPerformed
        
    }//GEN-LAST:event_btnNuevoForoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarForo;
    private javax.swing.JButton btnEntrarForo;
    private javax.swing.JButton btnNuevoForo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaForos;
    // End of variables declaration//GEN-END:variables
}
