/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.*;

/**
 *
 * @author alumnogreibd
 */
public final class VForos extends javax.swing.JFrame {
    
    FachadaAplicacion fa;
    Usuario usuario;
    int idProyecto;

    /**
     * Creates new form VForos
     * @param fa
     * @param usuario
     * @param idProyecto
     */
    public VForos(FachadaAplicacion fa, Usuario usuario, int idProyecto) {
        this.fa = fa;
        this.usuario = usuario;
        this.idProyecto = idProyecto;
        initComponents();
        
        if (usuario.getTipoUsuario() == TipoUsuario.Normal){
            btnNuevoForo.setVisible(false);
            btnBorrarForo.setVisible(false);
        }
        
        buscarForos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnEntrarForo = new javax.swing.JButton();
        btnNuevoForo = new javax.swing.JButton();
        btnBorrarForo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaForos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Foros");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEntrarForo.setText("Entrar");
        btnEntrarForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarForoActionPerformed(evt);
            }
        });

        btnNuevoForo.setText("Nuevo Foro");
        btnNuevoForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoForoActionPerformed(evt);
            }
        });

        btnBorrarForo.setText("Borrar Foro");
        btnBorrarForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarForoActionPerformed(evt);
            }
        });

        tablaForos.setModel(new ModeloTablaForos());
        jScrollPane2.setViewportView(tablaForos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEntrarForo)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevoForo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrarForo)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnEntrarForo)
                    .addComponent(btnNuevoForo)
                    .addComponent(btnBorrarForo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoForoActionPerformed
        fa.ventanaNuevoForo(idProyecto);
        buscarForos();
    }//GEN-LAST:event_btnNuevoForoActionPerformed

    private void btnBorrarForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarForoActionPerformed
        fa.borrarForo((int)((ModeloTablaForos)tablaForos.getModel()).getValueAt(tablaForos.getSelectedRow(), 0));
        buscarForos();
    }//GEN-LAST:event_btnBorrarForoActionPerformed

    private void btnEntrarForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarForoActionPerformed
        int idForo = (int)((ModeloTablaForos)tablaForos.getModel()).getValueAt(tablaForos.getSelectedRow(), 0);
        String nombreForo = (String)((ModeloTablaForos)tablaForos.getModel()).getValueAt(tablaForos.getSelectedRow(), 1);
        fa.ventanaPublicaciones(new Foro(idForo, nombreForo, idProyecto));
    }//GEN-LAST:event_btnEntrarForoActionPerformed

    private void buscarForos(){
        ModeloTablaForos m;

        m = (ModeloTablaForos) tablaForos.getModel();
        m.setFilas(fa.obtenerForos(idProyecto));
        if (m.getRowCount() > 0) {
            tablaForos.setRowSelectionInterval(0, 0);
            btnBorrarForo.setEnabled(true);
        } else {
            btnBorrarForo.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarForo;
    private javax.swing.JButton btnEntrarForo;
    private javax.swing.JButton btnNuevoForo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaForos;
    // End of variables declaration//GEN-END:variables
}
