/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * VPrincipal.java
 *
 * Created on 27-ene-2011, 10:31:24
 */
package gui;
import aplicacion.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author basesdatos
 */
public class VPrincipalUsuario extends javax.swing.JFrame {

    aplicacion.FachadaAplicacion fa;
    Usuario usuario;

    /**
     * Creates new form VPrincipal
     *
     * @param fa
     */
    public VPrincipalUsuario(FachadaAplicacion fa) {
        this.fa = fa;
        this.usuario = fa.getUsuario();
        initComponents();
      
        añadirNotificaciones();
      
        if (usuario.getTipoUsuario() == TipoUsuario.Gestor){
            btnEditarTarea.setEnabled(false);
            btnBorrarTarea.setEnabled(false);
            btnNuevaTarea.setEnabled(false);
            btnBuscar.setEnabled(false);
            buscaNombre.setEnabled(false);
            selecAscDesc.setEnabled(false);
            buscaCompletada.setEnabled(false);
            btnNotificacion.setEnabled(false);
        }
        
        if (!fa.obtenerNotificaciones().isEmpty()){
            btnNotificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/bell_act.png")));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        etiquetaTitulo = new javax.swing.JLabel();
        buscaNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTareas = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnNuevaTarea = new javax.swing.JButton();
        btnEditarTarea = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buscaCompletada = new javax.swing.JCheckBox();
        btnNotificacion = new javax.swing.JButton();
        selecAscDesc = new javax.swing.JComboBox<>();
        btnBorrarTarea = new javax.swing.JButton();
        btnProyectos = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa de Gestión de Tareas");
        setName("vPrincipal"); // NOI18N
        setResizable(false);

        jLabel1.setText("Nombre:");

        tablaTareas.setModel(new gui.ModeloTablaTareasBasicas(fa));
        tablaTareas.setColumnSelectionAllowed(true);
        tablaTareas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaTareas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaTareas);
        tablaTareas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNuevaTarea.setText("Nueva");
        btnNuevaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaTareaActionPerformed(evt);
            }
        });

        btnEditarTarea.setText("Editar");
        btnEditarTarea.setEnabled(false);
        btnEditarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTareaActionPerformed(evt);
            }
        });

        jLabel3.setText("Completada:");

        btnNotificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/bell.png"))); // NOI18N
        btnNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacionActionPerformed(evt);
            }
        });

        selecAscDesc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Descendente" }));

        btnBorrarTarea.setText("Borrar");
        btnBorrarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTareaActionPerformed(evt);
            }
        });

        btnProyectos.setText("Proyectos");
        btnProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyectosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNuevaTarea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBorrarTarea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditarTarea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProyectos)
                                .addGap(75, 75, 75)
                                .addComponent(btnSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaTitulo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscaNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscaCompletada)
                                .addGap(18, 18, 18)
                                .addComponent(selecAscDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar)))
                        .addGap(18, 18, 18)
                        .addComponent(btnNotificacion)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiquetaTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(buscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnBuscar)
                                .addComponent(selecAscDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buscaCompletada)
                                .addComponent(jLabel3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNotificacion)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnNuevaTarea)
                    .addComponent(btnEditarTarea)
                    .addComponent(btnBorrarTarea)
                    .addComponent(btnProyectos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Biblioteca Informática");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarTareas();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTareaActionPerformed
        ModeloTablaTareasBasicas mtb = (ModeloTablaTareasBasicas) tablaTareas.getModel();
        int idTarea;
        idTarea = mtb.obtenerTareas(tablaTareas.getSelectedRow()).getIdTarea();
        fa.visualizarTarea(idTarea);
        
    }//GEN-LAST:event_btnEditarTareaActionPerformed

    private void btnNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaTareaActionPerformed
        fa.nuevaTarea();
    }//GEN-LAST:event_btnNuevaTareaActionPerformed

    private void btnBorrarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTareaActionPerformed
        ModeloTablaTareasBasicas m;
        m = (ModeloTablaTareasBasicas) tablaTareas.getModel();
        int idTarea;
        idTarea = m.obtenerTareas(tablaTareas.getSelectedRow()).getIdTarea();
        fa.borrarTarea(idTarea);
        buscarTareas();

    }//GEN-LAST:event_btnBorrarTareaActionPerformed

    private void btnNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacionActionPerformed
        fa.ventanaNotificaciones();
    }//GEN-LAST:event_btnNotificacionActionPerformed

    private void btnProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyectosActionPerformed
        fa.nuevoVPrincipalProyectos();
    }//GEN-LAST:event_btnProyectosActionPerformed

    public void buscarTareas() {
        ModeloTablaTareasBasicas m;

        m = (ModeloTablaTareasBasicas) tablaTareas.getModel();
        m.setFilas(fa.obtenerTareas(buscaNombre.getText(), buscaCompletada.isSelected(), selecAscDesc.getSelectedIndex()));
        if (m.getRowCount() > 0) {
            tablaTareas.setRowSelectionInterval(0, 0);
            btnEditarTarea.setEnabled(true);
        } else {
            btnEditarTarea.setEnabled(false);
        }
    }
    

    public final void añadirNotificaciones(){
        List<String> listaDeStrings = new ArrayList<>();
        int min = 0;
        int max = 3;
        Random random = new Random();
        int numeroAleatorio = random.nextInt(max - min + 1) + min;
        listaDeStrings.add("La tarea '%s' termina pronto, ¡date prisa!");
        listaDeStrings.add("Queda 1 día para que la tarea '%s' termine, ¡ánimo!");
        listaDeStrings.add("¿Vas a dejar que la pereza te domine? ¡¡¡Acaba '%s'!!!");
        listaDeStrings.add("Todo el mundo confía en ti, tu puedes acabar '%s'");
        
        for (Tarea tarea: fa.notiTareaBasica()){
            String m = String.format(listaDeStrings.get(numeroAleatorio), tarea.getNombre());
            LocalDate fechaActual = LocalDate.now();
            Notificacion n = new Notificacion(-1, m, false, fechaActual, tarea.getIdTarea(), TipoNotificacion.Basica);
            fa.insertarNotificacionBasica(n);
            
        }
        for (Tarea tarea: fa.notiTareaProyecto()){
            String m = String.format("La tarea '%s' termina pronto, ¡date prisa!", tarea.getNombre());
            LocalDate fechaActual = LocalDate.now();
            Notificacion n = new Notificacion(-1, m, false, fechaActual, tarea.getIdTarea(), TipoNotificacion.Proyecto);
            fa.insertarNotificacionProyecto(n);
            
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarTarea;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditarTarea;
    private javax.swing.JButton btnNotificacion;
    private javax.swing.JButton btnNuevaTarea;
    private javax.swing.JButton btnProyectos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox buscaCompletada;
    private javax.swing.JTextField buscaNombre;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> selecAscDesc;
    private javax.swing.JTable tablaTareas;
    // End of variables declaration//GEN-END:variables
}
