/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.Categoria;
import aplicacion.FachadaAplicacion;
import aplicacion.Tarea;
import baseDatos.FachadaBaseDatos;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author loisf
 */
public class VTarea extends javax.swing.JFrame {

    private FachadaAplicacion fa;
    private Tarea tarea;
    private VPrincipalUsuario padre;
    private FachadaBaseDatos fbd; 
    private String idUsuario;

    /**
     * Creates new form VTarea
     * @param fa
     * @param restoCategorias
     * @param fbd
     * @param idUsuario
     */
    public VTarea(FachadaAplicacion fa, List<String> restoCategorias, FachadaBaseDatos fbd, String idUsuario) {
        this.fa = fa;
        this.fbd = fbd;
        this.idUsuario = idUsuario;
        initComponents();

        ModeloListaStrings mListaRC=new ModeloListaStrings();
        listaCategorias.setModel(mListaRC);
        mListaRC.setElementos(restoCategorias);
        btnAnhadirCategoria.setEnabled(false);
        
        btnQuitarCategoria.setEnabled(false);
        txtId.setEditable(false);
        //listaCategoriasActuales.setEditable(false);
    }
    
    public VTarea(FachadaAplicacion fa, List<String> restoCategorias, Tarea t, FachadaBaseDatos fbd){
        this.fa = fa;
        this.fbd = fbd;
        initComponents();
        ModeloListaStrings mListaRC=new ModeloListaStrings();
        listaCategorias.setModel(mListaRC);
        mListaRC.setElementos(restoCategorias);
        if (mListaRC.getSize()>0) {
            listaCategorias.setSelectedIndex(0);
            btnAnhadirCategoria.setEnabled(true);
        } else btnAnhadirCategoria.setEnabled(false);
        
        this.tarea = t;
        
        txtNombre.setText(tarea.getNombre());
        txtId.setText(((Integer)tarea.getIdTarea()).toString());
        checkCompletada.setSelected(tarea.getCompletada());
        txtFechaFin.setText(tarea.getFechaFin().toString());
        
        btnGuardarTarea.setEnabled(true);
        
        ModeloListaStrings mLRC=new ModeloListaStrings();
        listaCategoriasActuales.setModel(mLRC);
        ArrayList<String> nombreCategorias = new ArrayList<>();
        for (Categoria cat : t.getCategorias()){
            nombreCategorias.add(cat.getNombre());
        }
        mLRC.setElementos(nombreCategorias);
        
        btnQuitarCategoria.setEnabled(true);
        txtId.setEditable(false);
        //listaCategoriasActuales.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        checkCompletada = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        btnGuardarTarea = new javax.swing.JButton();
        btnSalirTarea = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCategoriasActuales = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        btnAnhadirCategoria = new javax.swing.JButton();
        btnQuitarCategoria = new javax.swing.JButton();
        btnSalirCategoria = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCategorias = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Tareas");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Id:");

        jLabel3.setText("Completada:");

        jLabel4.setText("Fecha de finalización:");

        btnGuardarTarea.setText("Guardar");
        btnGuardarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTareaActionPerformed(evt);
            }
        });

        btnSalirTarea.setText("Salir");
        btnSalirTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirTareaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardarTarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalirTarea))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkCompletada))
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(checkCompletada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarTarea)
                    .addComponent(btnSalirTarea))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tarea", jPanel1);

        jLabel5.setText("Categorías actuales");

        listaCategoriasActuales.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaCategoriasActuales);

        jLabel6.setText("Categorías disponibles");

        btnAnhadirCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaI.jpg"))); // NOI18N
        btnAnhadirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhadirCategoriaActionPerformed(evt);
            }
        });

        btnQuitarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaD.jpg"))); // NOI18N
        btnQuitarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarCategoriaActionPerformed(evt);
            }
        });

        btnSalirCategoria.setText("Salir");
        btnSalirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirCategoriaActionPerformed(evt);
            }
        });

        listaCategorias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaCategorias);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAnhadirCategoria)
                                    .addComponent(btnQuitarCategoria))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 46, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalirCategoria)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnAnhadirCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnQuitarCategoria)
                                .addGap(0, 49, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalirCategoria)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Categorías", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTareaActionPerformed
        if (txtNombre.getText().isBlank() || txtFechaFin.getText().isBlank()){
            System.out.println("Debes completar todos los campos excepto el Id");
            this.fa.muestraExcepcion("Debes completar todos los campos excepto el Id");
        }
        if (txtId.getText().isBlank()){
            Tarea t = new Tarea(-1, txtNombre.getText(), checkCompletada.isSelected(), LocalDate.parse(txtFechaFin.getText()), null);
            this.tarea = fa.anhadirTarea(t, idUsuario);
            if (listaCategoriasActuales.getModel().getSize() > 0){
                btnAnhadirCategoria.setEnabled(true);
            }
           
            return;
        }
        Tarea t;
        t = new Tarea(Integer.parseInt(txtId.getText()), txtNombre.getText(), checkCompletada.isSelected(), LocalDate.parse(txtFechaFin.getText()), tarea.getCategorias());

        fa.actualizarTarea(t);
    }//GEN-LAST:event_btnGuardarTareaActionPerformed

    private void btnSalirTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirTareaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirTareaActionPerformed

    private void btnAnhadirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhadirCategoriaActionPerformed
        Categoria cat = new Categoria(((ModeloListaStrings)listaCategorias.getModel()).getElementAt(listaCategorias.getSelectedIndex()));
        fa.cambiarCategoriaTarea(tarea.getIdTarea(), cat.getNombre());
        consultarTarea(tarea.getIdTarea());
        if (((ModeloListaStrings)listaCategoriasActuales.getModel()).getSize() > 0){
            btnQuitarCategoria.setEnabled(true);
        }
    }//GEN-LAST:event_btnAnhadirCategoriaActionPerformed

    private void btnSalirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirCategoriaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirCategoriaActionPerformed

    private void btnQuitarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarCategoriaActionPerformed
        fa.eliminarCategoriaTarea(tarea.getIdTarea(), 
                ((ModeloListaStrings)listaCategoriasActuales.getModel()).getElementAt(listaCategoriasActuales.getSelectedIndex()));
        consultarTarea(tarea.getIdTarea());
        
    }//GEN-LAST:event_btnQuitarCategoriaActionPerformed

    public void consultarTarea(int idTarea){
        Tarea tt = fa.consultarTarea(idTarea);
        this.tarea = tt;
        txtNombre.setText(tarea.getNombre());
        txtId.setText(((Integer)tarea.getIdTarea()).toString());
        checkCompletada.setSelected(tarea.getCompletada());
        txtFechaFin.setText(tarea.getFechaFin().toString());
        
        ArrayList<String> nombreCategorias = new ArrayList<>();
        for (Categoria cat : tt.getCategorias()){
            nombreCategorias.add(cat.getNombre());
        }
        ((ModeloListaStrings)listaCategoriasActuales.getModel()).setElementos(nombreCategorias);
        ((ModeloListaStrings)listaCategorias.getModel()).setElementos(fbd.obtenerRestoCategorias(tarea.getIdTarea()));
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnhadirCategoria;
    private javax.swing.JButton btnGuardarTarea;
    private javax.swing.JButton btnQuitarCategoria;
    private javax.swing.JButton btnSalirCategoria;
    private javax.swing.JButton btnSalirTarea;
    private javax.swing.JCheckBox checkCompletada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listaCategorias;
    private javax.swing.JList<String> listaCategoriasActuales;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
