drop table if exists Tener_notificacion_de_proyecto;
drop table if exists Categoria_tarea_basica;
drop table if exists Publicacion;
drop table if exists Participar;
drop table if exists Foro;
drop table if exists Notificacion_de_proyecto;
drop table if exists Notificacion_basica;
drop table if exists Subtarea;
drop table if exists Tarea_de_proyecto;
drop table if exists Tarea_basica;
drop table if exists Seccion;
drop table if exists Proyecto;
drop table if exists Gestionar_categoria;
drop table if exists Gestionar_usuario;
drop table if exists Categoria;
drop table if exists Usuario_gestor;
drop table if exists Administrador;
drop table if exists Usuario;
drop sequence if exists proyecto_id_seq;
drop sequence if exists seccion_id_seq;
drop sequence if exists tarea_basica_id_seq;
drop sequence if exists tarea_de_proyecto_id_seq;
drop sequence if exists subtarea_id_seq;
drop sequence if exists notificacion_basica_id_seq;
drop sequence if exists notificacion_de_proyecto_id_seq;
drop sequence if exists foro_id_seq;
drop sequence if exists publicacion_id_seq;
drop function if exists proyecto_auto_id();
drop trigger if exists proyecto_auto_id_trigger on Proyecto;
drop function if exists seccion_auto_id();
drop trigger if exists seccion_auto_id_trigger on Seccion;
drop function if exists tarea_basica_auto_id();
drop trigger if exists tarea_basica_auto_id_trigger on Tarea_basica;
drop function if exists tarea_de_proyecto_auto_id();
drop trigger if exists tarea_de_proyecto_auto_id_trigger on Tarea_de_proyecto;
drop function if exists subtarea_auto_id();
drop trigger if exists subtarea_auto_id_trigger on Subtarea;
drop function if exists notificacion_basica_auto_id();
drop trigger if exists notificacion_basica_auto_id_trigger on Notificacion_basica;
drop function if exists notificacion_de_proyecto_auto_id();
drop trigger if exists notificacion_de_proyecto_auto_id_trigger on Notificacion_de_proyecto;
drop function if exists foro_auto_id();
drop trigger if exists foro_auto_id_trigger on Foro;
drop function if exists publicacion_auto_id();
drop trigger if exists publicacion_auto_id_trigger on Publicacion;
